### ISSUE TITLE
J2store v4.0.3 under J4 not opening: Class 'J2Store' not found

### ISSUE THREAD

**Issue by ammfog** [J2Store4/j2store4#41]
Migration done exactly after documentation: migrationchecker and installing under J3. Worked.
Under J4, the component not opening. Instead error: Class 'J2Store' not found.

**Comment by mgopin3** [comment]
I can understand your concern.

This issue might be caused by using an outdated version of the FOF library on your site. In this case, I recommend that you install the latest version of the FOF library. After installing the latest version of the FOF library, please attempt to install the latest release of J2Store v4 (4.0.3-Pro) on your site.

By completing these steps, the issue should be resolved. If you continue to experience the same issue on your site, please don't hesitate to let us know. Please enable the debug mode and send a reference image for the issue that you are facing.

You can download the latest version of the FOF library https://github.com/J2Store4/fof/releases

**Comment by ammfog** [comment]
Thank you very much for your response. I did exactly what you said: installed the latest fof version first and afterwards installed the latest j2store pro version. Unfortunately, the error is still there... See the screenshot attached.

![screenshot](https://github.com/J2Store4/j2store4/assets/148993227/dc259c6d-0927-4b0a-85b4-2d4d36b3fac9)

**Comment by mgopin3** [comment]
I can understand your concern. We have reproduced this issue on our local site. If you have disabled the J2Store system plugin on your site, this error will exist. In this case, I suggest you Go to the "**System**" and then "**Manage Extensions**." You will find the "**system-J2Store** " plugin there. Please enable this plugin. After completing this change, the issue should be resolved.
Please check this image for your reference:-https://tinyurl.com/ylarny3c

If you continue to experience the same issue on your site, please don't hesitate to let us know. Please enable the debug mode and send a reference image of the issue you are facing.

**Comment by ammfog** [comment]
Yes, it is working now after enabling the mentioned system plugin. Thank you so much!!!

**Comment by ammfog** [comment]
..

**Comment by mgopin3** [comment]
@ammfog We believe the reported issue has been addressed. Could you please confirm that the problem is resolved on your end? If everything looks good, we'll go ahead and close this issue.

If you have any further questions or if there's anything else you'd like assistance with, please don't hesitate to let us know. We appreciate your feedback!
